(define (problem prob_d2_t2_l4_p3_c6)
(:domain emergencias-temporal)
(:objects
	dron1 dron2 - dron
	deposito refugio1 refugio2 refugio3 refugio4 - location
	box1 box2 box3 box4 box5 box6 - box
	comida medicina - bcontent
	person1 person2 person3 - person
	carrier1 carrier2 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(= (fly-cost deposito refugio1) 3)
	(= (fly-cost deposito refugio2) 7)
	(= (fly-cost deposito refugio3) 8)
	(= (fly-cost deposito refugio4) 17)
	(= (fly-cost refugio1 deposito) 20)
	(= (fly-cost refugio1 refugio2) 1)
	(= (fly-cost refugio1 refugio3) 18)
	(= (fly-cost refugio1 refugio4) 7)
	(= (fly-cost refugio2 deposito) 18)
	(= (fly-cost refugio2 refugio1) 14)
	(= (fly-cost refugio2 refugio3) 8)
	(= (fly-cost refugio2 refugio4) 15)
	(= (fly-cost refugio3 deposito) 19)
	(= (fly-cost refugio3 refugio1) 9)
	(= (fly-cost refugio3 refugio2) 1)
	(= (fly-cost refugio3 refugio4) 6)
	(= (fly-cost refugio4 deposito) 14)
	(= (fly-cost refugio4 refugio1) 11)
	(= (fly-cost refugio4 refugio2) 9)
	(= (fly-cost refugio4 refugio3) 5)
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)
	(at-dron dron1 deposito)
	(free dron1)
	(dron-available dron1)
	(at-dron dron2 deposito)
	(free dron2)
	(dron-available dron2)
	(at-carrier carrier1 deposito)
	(boxes-in-carrier carrier1 n0)
	(carrier-available carrier1)
	(at-carrier carrier2 deposito)
	(boxes-in-carrier carrier2 n0)
	(carrier-available carrier2)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 comida)
	(at-box box6 deposito)
	(box-has box6 medicina)
	(at-person person1 refugio2)
	(person-available person1)
	(at-person person2 refugio3)
	(person-available person2)
	(at-person person3 refugio1)
	(person-available person3)
)

(:goal (and
	(person-has person1 comida)
	(person-has person3 comida)
	(person-has person3 medicina)
))
(:metric minimize (total-time))
)
