(define (problem prob_d1_t1_l4_p5_c10)
(:domain emergencias-temporal)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 - location
	box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 - person
	carrier1 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(= (fly-cost deposito refugio1) 19)
	(= (fly-cost deposito refugio2) 9)
	(= (fly-cost deposito refugio3) 1)
	(= (fly-cost deposito refugio4) 6)
	(= (fly-cost refugio1 deposito) 14)
	(= (fly-cost refugio1 refugio2) 11)
	(= (fly-cost refugio1 refugio3) 9)
	(= (fly-cost refugio1 refugio4) 5)
	(= (fly-cost refugio2 deposito) 7)
	(= (fly-cost refugio2 refugio1) 11)
	(= (fly-cost refugio2 refugio3) 4)
	(= (fly-cost refugio2 refugio4) 3)
	(= (fly-cost refugio3 deposito) 13)
	(= (fly-cost refugio3 refugio1) 4)
	(= (fly-cost refugio3 refugio2) 12)
	(= (fly-cost refugio3 refugio4) 12)
	(= (fly-cost refugio4 deposito) 20)
	(= (fly-cost refugio4 refugio1) 9)
	(= (fly-cost refugio4 refugio2) 2)
	(= (fly-cost refugio4 refugio3) 15)
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)
	(at-dron dron1 deposito)
	(free dron1)
	(dron-available dron1)
	(at-carrier carrier1 deposito)
	(boxes-in-carrier carrier1 n0)
	(carrier-available carrier1)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 comida)
	(at-box box6 deposito)
	(box-has box6 comida)
	(at-box box7 deposito)
	(box-has box7 comida)
	(at-box box8 deposito)
	(box-has box8 comida)
	(at-box box9 deposito)
	(box-has box9 medicina)
	(at-box box10 deposito)
	(box-has box10 medicina)
	(at-person person1 refugio1)
	(person-available person1)
	(at-person person2 refugio4)
	(person-available person2)
	(at-person person3 refugio1)
	(person-available person3)
	(at-person person4 refugio3)
	(person-available person4)
	(at-person person5 refugio3)
	(person-available person5)
)

(:goal (and
	(person-has person1 comida)
	(person-has person2 comida)
	(person-has person2 medicina)
	(person-has person5 comida)
	(person-has person5 medicina)
))
(:metric minimize (total-time))
)
