(define (problem problem_size9)
(:domain emergencias-costs)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 refugio8 refugio9 - location
	box1 box2 box3 box4 box5 box6 box7 box8 box9 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 person6 person7 person8 person9 - person
	carrier1 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(= (total-cost) 0)
	(= (fly-cost deposito refugio1) 17)
	(= (fly-cost deposito refugio2) 8)
	(= (fly-cost deposito refugio3) 16)
	(= (fly-cost deposito refugio4) 5)
	(= (fly-cost deposito refugio5) 16)
	(= (fly-cost deposito refugio6) 20)
	(= (fly-cost deposito refugio7) 19)
	(= (fly-cost deposito refugio8) 4)
	(= (fly-cost deposito refugio9) 18)
	(= (fly-cost refugio1 deposito) 19)
	(= (fly-cost refugio1 refugio2) 17)
	(= (fly-cost refugio1 refugio3) 17)
	(= (fly-cost refugio1 refugio4) 4)
	(= (fly-cost refugio1 refugio5) 2)
	(= (fly-cost refugio1 refugio6) 17)
	(= (fly-cost refugio1 refugio7) 14)
	(= (fly-cost refugio1 refugio8) 13)
	(= (fly-cost refugio1 refugio9) 13)
	(= (fly-cost refugio2 deposito) 10)
	(= (fly-cost refugio2 refugio1) 1)
	(= (fly-cost refugio2 refugio3) 3)
	(= (fly-cost refugio2 refugio4) 15)
	(= (fly-cost refugio2 refugio5) 5)
	(= (fly-cost refugio2 refugio6) 6)
	(= (fly-cost refugio2 refugio7) 8)
	(= (fly-cost refugio2 refugio8) 11)
	(= (fly-cost refugio2 refugio9) 7)
	(= (fly-cost refugio3 deposito) 7)
	(= (fly-cost refugio3 refugio1) 9)
	(= (fly-cost refugio3 refugio2) 18)
	(= (fly-cost refugio3 refugio4) 15)
	(= (fly-cost refugio3 refugio5) 4)
	(= (fly-cost refugio3 refugio6) 2)
	(= (fly-cost refugio3 refugio7) 9)
	(= (fly-cost refugio3 refugio8) 19)
	(= (fly-cost refugio3 refugio9) 3)
	(= (fly-cost refugio4 deposito) 10)
	(= (fly-cost refugio4 refugio1) 1)
	(= (fly-cost refugio4 refugio2) 9)
	(= (fly-cost refugio4 refugio3) 17)
	(= (fly-cost refugio4 refugio5) 12)
	(= (fly-cost refugio4 refugio6) 5)
	(= (fly-cost refugio4 refugio7) 6)
	(= (fly-cost refugio4 refugio8) 5)
	(= (fly-cost refugio4 refugio9) 1)
	(= (fly-cost refugio5 deposito) 8)
	(= (fly-cost refugio5 refugio1) 16)
	(= (fly-cost refugio5 refugio2) 5)
	(= (fly-cost refugio5 refugio3) 2)
	(= (fly-cost refugio5 refugio4) 8)
	(= (fly-cost refugio5 refugio6) 4)
	(= (fly-cost refugio5 refugio7) 12)
	(= (fly-cost refugio5 refugio8) 5)
	(= (fly-cost refugio5 refugio9) 5)
	(= (fly-cost refugio6 deposito) 2)
	(= (fly-cost refugio6 refugio1) 15)
	(= (fly-cost refugio6 refugio2) 7)
	(= (fly-cost refugio6 refugio3) 3)
	(= (fly-cost refugio6 refugio4) 7)
	(= (fly-cost refugio6 refugio5) 12)
	(= (fly-cost refugio6 refugio7) 12)
	(= (fly-cost refugio6 refugio8) 13)
	(= (fly-cost refugio6 refugio9) 6)
	(= (fly-cost refugio7 deposito) 1)
	(= (fly-cost refugio7 refugio1) 3)
	(= (fly-cost refugio7 refugio2) 2)
	(= (fly-cost refugio7 refugio3) 12)
	(= (fly-cost refugio7 refugio4) 4)
	(= (fly-cost refugio7 refugio5) 5)
	(= (fly-cost refugio7 refugio6) 10)
	(= (fly-cost refugio7 refugio8) 8)
	(= (fly-cost refugio7 refugio9) 14)
	(= (fly-cost refugio8 deposito) 19)
	(= (fly-cost refugio8 refugio1) 10)
	(= (fly-cost refugio8 refugio2) 1)
	(= (fly-cost refugio8 refugio3) 18)
	(= (fly-cost refugio8 refugio4) 12)
	(= (fly-cost refugio8 refugio5) 5)
	(= (fly-cost refugio8 refugio6) 6)
	(= (fly-cost refugio8 refugio7) 16)
	(= (fly-cost refugio8 refugio9) 20)
	(= (fly-cost refugio9 deposito) 13)
	(= (fly-cost refugio9 refugio1) 5)
	(= (fly-cost refugio9 refugio2) 1)
	(= (fly-cost refugio9 refugio3) 4)
	(= (fly-cost refugio9 refugio4) 17)
	(= (fly-cost refugio9 refugio5) 11)
	(= (fly-cost refugio9 refugio6) 3)
	(= (fly-cost refugio9 refugio7) 9)
	(= (fly-cost refugio9 refugio8) 17)
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)
	(at-dron dron1 deposito)
	(free dron1)
	(at-carrier carrier1 deposito)
	(boxes-in-carrier carrier1 n0)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 medicina)
	(at-box box5 deposito)
	(box-has box5 medicina)
	(at-box box6 deposito)
	(box-has box6 medicina)
	(at-box box7 deposito)
	(box-has box7 medicina)
	(at-box box8 deposito)
	(box-has box8 medicina)
	(at-box box9 deposito)
	(box-has box9 medicina)
	(at-person person1 refugio5)
	(at-person person2 refugio3)
	(at-person person3 refugio4)
	(at-person person4 refugio8)
	(at-person person5 refugio8)
	(at-person person6 refugio5)
	(at-person person7 refugio4)
	(at-person person8 refugio6)
	(at-person person9 refugio7)
)

(:goal (and
	(person-has person1 medicina)
	(person-has person2 medicina)
	(person-has person3 medicina)
	(person-has person4 comida)
	(person-has person5 comida)
	(person-has person5 medicina)
	(person-has person7 comida)
	(person-has person8 medicina)
	(person-has person9 medicina)
))
(:metric minimize (total-cost))
)