(define (problem problem_size13)
(:domain emergencias-costs)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 refugio8 refugio9 refugio10 refugio11 refugio12 refugio13 - location
	box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 box11 box12 box13 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 - person
	carrier1 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(= (total-cost) 0)
	(= (fly-cost deposito refugio1) 1)
	(= (fly-cost deposito refugio2) 12)
	(= (fly-cost deposito refugio3) 8)
	(= (fly-cost deposito refugio4) 7)
	(= (fly-cost deposito refugio5) 18)
	(= (fly-cost deposito refugio6) 5)
	(= (fly-cost deposito refugio7) 12)
	(= (fly-cost deposito refugio8) 6)
	(= (fly-cost deposito refugio9) 4)
	(= (fly-cost deposito refugio10) 4)
	(= (fly-cost deposito refugio11) 3)
	(= (fly-cost deposito refugio12) 20)
	(= (fly-cost deposito refugio13) 14)
	(= (fly-cost refugio1 deposito) 6)
	(= (fly-cost refugio1 refugio2) 2)
	(= (fly-cost refugio1 refugio3) 8)
	(= (fly-cost refugio1 refugio4) 16)
	(= (fly-cost refugio1 refugio5) 7)
	(= (fly-cost refugio1 refugio6) 7)
	(= (fly-cost refugio1 refugio7) 14)
	(= (fly-cost refugio1 refugio8) 3)
	(= (fly-cost refugio1 refugio9) 4)
	(= (fly-cost refugio1 refugio10) 20)
	(= (fly-cost refugio1 refugio11) 17)
	(= (fly-cost refugio1 refugio12) 8)
	(= (fly-cost refugio1 refugio13) 5)
	(= (fly-cost refugio2 deposito) 12)
	(= (fly-cost refugio2 refugio1) 4)
	(= (fly-cost refugio2 refugio3) 18)
	(= (fly-cost refugio2 refugio4) 1)
	(= (fly-cost refugio2 refugio5) 4)
	(= (fly-cost refugio2 refugio6) 19)
	(= (fly-cost refugio2 refugio7) 19)
	(= (fly-cost refugio2 refugio8) 13)
	(= (fly-cost refugio2 refugio9) 6)
	(= (fly-cost refugio2 refugio10) 18)
	(= (fly-cost refugio2 refugio11) 5)
	(= (fly-cost refugio2 refugio12) 14)
	(= (fly-cost refugio2 refugio13) 19)
	(= (fly-cost refugio3 deposito) 8)
	(= (fly-cost refugio3 refugio1) 7)
	(= (fly-cost refugio3 refugio2) 19)
	(= (fly-cost refugio3 refugio4) 9)
	(= (fly-cost refugio3 refugio5) 18)
	(= (fly-cost refugio3 refugio6) 1)
	(= (fly-cost refugio3 refugio7) 9)
	(= (fly-cost refugio3 refugio8) 14)
	(= (fly-cost refugio3 refugio9) 2)
	(= (fly-cost refugio3 refugio10) 20)
	(= (fly-cost refugio3 refugio11) 18)
	(= (fly-cost refugio3 refugio12) 5)
	(= (fly-cost refugio3 refugio13) 10)
	(= (fly-cost refugio4 deposito) 16)
	(= (fly-cost refugio4 refugio1) 14)
	(= (fly-cost refugio4 refugio2) 4)
	(= (fly-cost refugio4 refugio3) 10)
	(= (fly-cost refugio4 refugio5) 17)
	(= (fly-cost refugio4 refugio6) 5)
	(= (fly-cost refugio4 refugio7) 3)
	(= (fly-cost refugio4 refugio8) 2)
	(= (fly-cost refugio4 refugio9) 12)
	(= (fly-cost refugio4 refugio10) 20)
	(= (fly-cost refugio4 refugio11) 10)
	(= (fly-cost refugio4 refugio12) 4)
	(= (fly-cost refugio4 refugio13) 11)
	(= (fly-cost refugio5 deposito) 7)
	(= (fly-cost refugio5 refugio1) 4)
	(= (fly-cost refugio5 refugio2) 3)
	(= (fly-cost refugio5 refugio3) 18)
	(= (fly-cost refugio5 refugio4) 20)
	(= (fly-cost refugio5 refugio6) 7)
	(= (fly-cost refugio5 refugio7) 1)
	(= (fly-cost refugio5 refugio8) 14)
	(= (fly-cost refugio5 refugio9) 5)
	(= (fly-cost refugio5 refugio10) 19)
	(= (fly-cost refugio5 refugio11) 1)
	(= (fly-cost refugio5 refugio12) 14)
	(= (fly-cost refugio5 refugio13) 16)
	(= (fly-cost refugio6 deposito) 19)
	(= (fly-cost refugio6 refugio1) 4)
	(= (fly-cost refugio6 refugio2) 16)
	(= (fly-cost refugio6 refugio3) 11)
	(= (fly-cost refugio6 refugio4) 10)
	(= (fly-cost refugio6 refugio5) 17)
	(= (fly-cost refugio6 refugio7) 17)
	(= (fly-cost refugio6 refugio8) 8)
	(= (fly-cost refugio6 refugio9) 12)
	(= (fly-cost refugio6 refugio10) 15)
	(= (fly-cost refugio6 refugio11) 1)
	(= (fly-cost refugio6 refugio12) 18)
	(= (fly-cost refugio6 refugio13) 20)
	(= (fly-cost refugio7 deposito) 15)
	(= (fly-cost refugio7 refugio1) 9)
	(= (fly-cost refugio7 refugio2) 10)
	(= (fly-cost refugio7 refugio3) 16)
	(= (fly-cost refugio7 refugio4) 7)
	(= (fly-cost refugio7 refugio5) 9)
	(= (fly-cost refugio7 refugio6) 18)
	(= (fly-cost refugio7 refugio8) 1)
	(= (fly-cost refugio7 refugio9) 13)
	(= (fly-cost refugio7 refugio10) 13)
	(= (fly-cost refugio7 refugio11) 6)
	(= (fly-cost refugio7 refugio12) 14)
	(= (fly-cost refugio7 refugio13) 1)
	(= (fly-cost refugio8 deposito) 8)
	(= (fly-cost refugio8 refugio1) 8)
	(= (fly-cost refugio8 refugio2) 9)
	(= (fly-cost refugio8 refugio3) 12)
	(= (fly-cost refugio8 refugio4) 2)
	(= (fly-cost refugio8 refugio5) 9)
	(= (fly-cost refugio8 refugio6) 7)
	(= (fly-cost refugio8 refugio7) 14)
	(= (fly-cost refugio8 refugio9) 19)
	(= (fly-cost refugio8 refugio10) 16)
	(= (fly-cost refugio8 refugio11) 14)
	(= (fly-cost refugio8 refugio12) 8)
	(= (fly-cost refugio8 refugio13) 7)
	(= (fly-cost refugio9 deposito) 4)
	(= (fly-cost refugio9 refugio1) 8)
	(= (fly-cost refugio9 refugio2) 19)
	(= (fly-cost refugio9 refugio3) 15)
	(= (fly-cost refugio9 refugio4) 7)
	(= (fly-cost refugio9 refugio5) 7)
	(= (fly-cost refugio9 refugio6) 9)
	(= (fly-cost refugio9 refugio7) 16)
	(= (fly-cost refugio9 refugio8) 11)
	(= (fly-cost refugio9 refugio10) 1)
	(= (fly-cost refugio9 refugio11) 11)
	(= (fly-cost refugio9 refugio12) 9)
	(= (fly-cost refugio9 refugio13) 5)
	(= (fly-cost refugio10 deposito) 14)
	(= (fly-cost refugio10 refugio1) 4)
	(= (fly-cost refugio10 refugio2) 6)
	(= (fly-cost refugio10 refugio3) 18)
	(= (fly-cost refugio10 refugio4) 12)
	(= (fly-cost refugio10 refugio5) 2)
	(= (fly-cost refugio10 refugio6) 5)
	(= (fly-cost refugio10 refugio7) 17)
	(= (fly-cost refugio10 refugio8) 7)
	(= (fly-cost refugio10 refugio9) 20)
	(= (fly-cost refugio10 refugio11) 12)
	(= (fly-cost refugio10 refugio12) 12)
	(= (fly-cost refugio10 refugio13) 9)
	(= (fly-cost refugio11 deposito) 2)
	(= (fly-cost refugio11 refugio1) 18)
	(= (fly-cost refugio11 refugio2) 6)
	(= (fly-cost refugio11 refugio3) 15)
	(= (fly-cost refugio11 refugio4) 14)
	(= (fly-cost refugio11 refugio5) 5)
	(= (fly-cost refugio11 refugio6) 7)
	(= (fly-cost refugio11 refugio7) 11)
	(= (fly-cost refugio11 refugio8) 17)
	(= (fly-cost refugio11 refugio9) 10)
	(= (fly-cost refugio11 refugio10) 16)
	(= (fly-cost refugio11 refugio12) 16)
	(= (fly-cost refugio11 refugio13) 15)
	(= (fly-cost refugio12 deposito) 17)
	(= (fly-cost refugio12 refugio1) 19)
	(= (fly-cost refugio12 refugio2) 1)
	(= (fly-cost refugio12 refugio3) 17)
	(= (fly-cost refugio12 refugio4) 12)
	(= (fly-cost refugio12 refugio5) 7)
	(= (fly-cost refugio12 refugio6) 13)
	(= (fly-cost refugio12 refugio7) 1)
	(= (fly-cost refugio12 refugio8) 20)
	(= (fly-cost refugio12 refugio9) 12)
	(= (fly-cost refugio12 refugio10) 7)
	(= (fly-cost refugio12 refugio11) 17)
	(= (fly-cost refugio12 refugio13) 10)
	(= (fly-cost refugio13 deposito) 3)
	(= (fly-cost refugio13 refugio1) 18)
	(= (fly-cost refugio13 refugio2) 12)
	(= (fly-cost refugio13 refugio3) 15)
	(= (fly-cost refugio13 refugio4) 1)
	(= (fly-cost refugio13 refugio5) 3)
	(= (fly-cost refugio13 refugio6) 10)
	(= (fly-cost refugio13 refugio7) 9)
	(= (fly-cost refugio13 refugio8) 13)
	(= (fly-cost refugio13 refugio9) 7)
	(= (fly-cost refugio13 refugio10) 17)
	(= (fly-cost refugio13 refugio11) 4)
	(= (fly-cost refugio13 refugio12) 2)
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)
	(at-dron dron1 deposito)
	(free dron1)
	(at-carrier carrier1 deposito)
	(boxes-in-carrier carrier1 n0)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 comida)
	(at-box box6 deposito)
	(box-has box6 comida)
	(at-box box7 deposito)
	(box-has box7 medicina)
	(at-box box8 deposito)
	(box-has box8 medicina)
	(at-box box9 deposito)
	(box-has box9 medicina)
	(at-box box10 deposito)
	(box-has box10 medicina)
	(at-box box11 deposito)
	(box-has box11 medicina)
	(at-box box12 deposito)
	(box-has box12 medicina)
	(at-box box13 deposito)
	(box-has box13 medicina)
	(at-person person1 refugio2)
	(at-person person2 refugio4)
	(at-person person3 refugio1)
	(at-person person4 refugio12)
	(at-person person5 refugio3)
	(at-person person6 refugio13)
	(at-person person7 refugio4)
	(at-person person8 refugio11)
	(at-person person9 refugio1)
	(at-person person10 refugio13)
	(at-person person11 refugio1)
	(at-person person12 refugio7)
	(at-person person13 refugio13)
)

(:goal (and
	(person-has person1 comida)
	(person-has person1 medicina)
	(person-has person3 comida)
	(person-has person4 comida)
	(person-has person4 medicina)
	(person-has person5 comida)
	(person-has person5 medicina)
	(person-has person9 comida)
	(person-has person9 medicina)
	(person-has person11 medicina)
	(person-has person12 comida)
	(person-has person12 medicina)
	(person-has person13 medicina)
))
(:metric minimize (total-cost))
)