(define (problem problem_size10)
(:domain emergencias-costs)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 refugio8 refugio9 refugio10 - location
	box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 - person
	carrier1 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(= (total-cost) 0)
	(= (fly-cost deposito refugio1) 1)
	(= (fly-cost deposito refugio2) 7)
	(= (fly-cost deposito refugio3) 16)
	(= (fly-cost deposito refugio4) 18)
	(= (fly-cost deposito refugio5) 16)
	(= (fly-cost deposito refugio6) 5)
	(= (fly-cost deposito refugio7) 8)
	(= (fly-cost deposito refugio8) 9)
	(= (fly-cost deposito refugio9) 18)
	(= (fly-cost deposito refugio10) 6)
	(= (fly-cost refugio1 deposito) 14)
	(= (fly-cost refugio1 refugio2) 1)
	(= (fly-cost refugio1 refugio3) 16)
	(= (fly-cost refugio1 refugio4) 18)
	(= (fly-cost refugio1 refugio5) 2)
	(= (fly-cost refugio1 refugio6) 15)
	(= (fly-cost refugio1 refugio7) 17)
	(= (fly-cost refugio1 refugio8) 3)
	(= (fly-cost refugio1 refugio9) 10)
	(= (fly-cost refugio1 refugio10) 8)
	(= (fly-cost refugio2 deposito) 1)
	(= (fly-cost refugio2 refugio1) 18)
	(= (fly-cost refugio2 refugio3) 5)
	(= (fly-cost refugio2 refugio4) 19)
	(= (fly-cost refugio2 refugio5) 18)
	(= (fly-cost refugio2 refugio6) 18)
	(= (fly-cost refugio2 refugio7) 17)
	(= (fly-cost refugio2 refugio8) 11)
	(= (fly-cost refugio2 refugio9) 10)
	(= (fly-cost refugio2 refugio10) 13)
	(= (fly-cost refugio3 deposito) 14)
	(= (fly-cost refugio3 refugio1) 17)
	(= (fly-cost refugio3 refugio2) 2)
	(= (fly-cost refugio3 refugio4) 9)
	(= (fly-cost refugio3 refugio5) 10)
	(= (fly-cost refugio3 refugio6) 1)
	(= (fly-cost refugio3 refugio7) 14)
	(= (fly-cost refugio3 refugio8) 17)
	(= (fly-cost refugio3 refugio9) 8)
	(= (fly-cost refugio3 refugio10) 5)
	(= (fly-cost refugio4 deposito) 17)
	(= (fly-cost refugio4 refugio1) 13)
	(= (fly-cost refugio4 refugio2) 14)
	(= (fly-cost refugio4 refugio3) 3)
	(= (fly-cost refugio4 refugio5) 7)
	(= (fly-cost refugio4 refugio6) 20)
	(= (fly-cost refugio4 refugio7) 19)
	(= (fly-cost refugio4 refugio8) 14)
	(= (fly-cost refugio4 refugio9) 6)
	(= (fly-cost refugio4 refugio10) 6)
	(= (fly-cost refugio5 deposito) 15)
	(= (fly-cost refugio5 refugio1) 5)
	(= (fly-cost refugio5 refugio2) 18)
	(= (fly-cost refugio5 refugio3) 9)
	(= (fly-cost refugio5 refugio4) 17)
	(= (fly-cost refugio5 refugio6) 19)
	(= (fly-cost refugio5 refugio7) 16)
	(= (fly-cost refugio5 refugio8) 20)
	(= (fly-cost refugio5 refugio9) 17)
	(= (fly-cost refugio5 refugio10) 12)
	(= (fly-cost refugio6 deposito) 14)
	(= (fly-cost refugio6 refugio1) 16)
	(= (fly-cost refugio6 refugio2) 14)
	(= (fly-cost refugio6 refugio3) 10)
	(= (fly-cost refugio6 refugio4) 2)
	(= (fly-cost refugio6 refugio5) 19)
	(= (fly-cost refugio6 refugio7) 12)
	(= (fly-cost refugio6 refugio8) 1)
	(= (fly-cost refugio6 refugio9) 7)
	(= (fly-cost refugio6 refugio10) 1)
	(= (fly-cost refugio7 deposito) 4)
	(= (fly-cost refugio7 refugio1) 16)
	(= (fly-cost refugio7 refugio2) 5)
	(= (fly-cost refugio7 refugio3) 16)
	(= (fly-cost refugio7 refugio4) 20)
	(= (fly-cost refugio7 refugio5) 2)
	(= (fly-cost refugio7 refugio6) 12)
	(= (fly-cost refugio7 refugio8) 3)
	(= (fly-cost refugio7 refugio9) 20)
	(= (fly-cost refugio7 refugio10) 18)
	(= (fly-cost refugio8 deposito) 2)
	(= (fly-cost refugio8 refugio1) 19)
	(= (fly-cost refugio8 refugio2) 20)
	(= (fly-cost refugio8 refugio3) 16)
	(= (fly-cost refugio8 refugio4) 17)
	(= (fly-cost refugio8 refugio5) 12)
	(= (fly-cost refugio8 refugio6) 13)
	(= (fly-cost refugio8 refugio7) 8)
	(= (fly-cost refugio8 refugio9) 19)
	(= (fly-cost refugio8 refugio10) 7)
	(= (fly-cost refugio9 deposito) 7)
	(= (fly-cost refugio9 refugio1) 19)
	(= (fly-cost refugio9 refugio2) 2)
	(= (fly-cost refugio9 refugio3) 16)
	(= (fly-cost refugio9 refugio4) 19)
	(= (fly-cost refugio9 refugio5) 1)
	(= (fly-cost refugio9 refugio6) 7)
	(= (fly-cost refugio9 refugio7) 19)
	(= (fly-cost refugio9 refugio8) 7)
	(= (fly-cost refugio9 refugio10) 12)
	(= (fly-cost refugio10 deposito) 7)
	(= (fly-cost refugio10 refugio1) 20)
	(= (fly-cost refugio10 refugio2) 3)
	(= (fly-cost refugio10 refugio3) 18)
	(= (fly-cost refugio10 refugio4) 12)
	(= (fly-cost refugio10 refugio5) 12)
	(= (fly-cost refugio10 refugio6) 19)
	(= (fly-cost refugio10 refugio7) 7)
	(= (fly-cost refugio10 refugio8) 5)
	(= (fly-cost refugio10 refugio9) 15)
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)
	(at-dron dron1 deposito)
	(free dron1)
	(at-carrier carrier1 deposito)
	(boxes-in-carrier carrier1 n0)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 medicina)
	(at-box box6 deposito)
	(box-has box6 medicina)
	(at-box box7 deposito)
	(box-has box7 medicina)
	(at-box box8 deposito)
	(box-has box8 medicina)
	(at-box box9 deposito)
	(box-has box9 medicina)
	(at-box box10 deposito)
	(box-has box10 medicina)
	(at-person person1 refugio10)
	(at-person person2 refugio1)
	(at-person person3 refugio6)
	(at-person person4 refugio7)
	(at-person person5 refugio10)
	(at-person person6 refugio3)
	(at-person person7 refugio5)
	(at-person person8 refugio10)
	(at-person person9 refugio7)
	(at-person person10 refugio10)
)

(:goal (and
	(person-has person1 comida)
	(person-has person3 medicina)
	(person-has person4 medicina)
	(person-has person5 medicina)
	(person-has person6 comida)
	(person-has person6 medicina)
	(person-has person7 comida)
	(person-has person9 comida)
	(person-has person9 medicina)
	(person-has person10 medicina)
))
(:metric minimize (total-cost))
)