(define (problem problem_size5)
(:domain emergencias-costs)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 refugio5 - location
	box1 box2 box3 box4 box5 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 - person
	carrier1 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(= (total-cost) 0)
	(= (fly-cost deposito refugio1) 3)
	(= (fly-cost deposito refugio2) 14)
	(= (fly-cost deposito refugio3) 17)
	(= (fly-cost deposito refugio4) 5)
	(= (fly-cost deposito refugio5) 1)
	(= (fly-cost refugio1 deposito) 15)
	(= (fly-cost refugio1 refugio2) 3)
	(= (fly-cost refugio1 refugio3) 14)
	(= (fly-cost refugio1 refugio4) 17)
	(= (fly-cost refugio1 refugio5) 5)
	(= (fly-cost refugio2 deposito) 4)
	(= (fly-cost refugio2 refugio1) 5)
	(= (fly-cost refugio2 refugio3) 2)
	(= (fly-cost refugio2 refugio4) 2)
	(= (fly-cost refugio2 refugio5) 20)
	(= (fly-cost refugio3 deposito) 6)
	(= (fly-cost refugio3 refugio1) 9)
	(= (fly-cost refugio3 refugio2) 1)
	(= (fly-cost refugio3 refugio4) 17)
	(= (fly-cost refugio3 refugio5) 8)
	(= (fly-cost refugio4 deposito) 17)
	(= (fly-cost refugio4 refugio1) 9)
	(= (fly-cost refugio4 refugio2) 17)
	(= (fly-cost refugio4 refugio3) 1)
	(= (fly-cost refugio4 refugio5) 1)
	(= (fly-cost refugio5 deposito) 18)
	(= (fly-cost refugio5 refugio1) 8)
	(= (fly-cost refugio5 refugio2) 17)
	(= (fly-cost refugio5 refugio3) 9)
	(= (fly-cost refugio5 refugio4) 6)
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)
	(at-dron dron1 deposito)
	(free dron1)
	(at-carrier carrier1 deposito)
	(boxes-in-carrier carrier1 n0)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 medicina)
	(at-person person1 refugio4)
	(at-person person2 refugio3)
	(at-person person3 refugio3)
	(at-person person4 refugio4)
	(at-person person5 refugio1)
)

(:goal (and
	(person-has person2 comida)
	(person-has person2 medicina)
	(person-has person3 comida)
	(person-has person4 comida)
	(person-has person5 comida)
))
(:metric minimize (total-cost))
)