(define (problem problem_size7)
(:domain emergencias-costs)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 - location
	box1 box2 box3 box4 box5 box6 box7 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 person6 person7 - person
	carrier1 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(= (total-cost) 0)
	(= (fly-cost deposito refugio1) 14)
	(= (fly-cost deposito refugio2) 20)
	(= (fly-cost deposito refugio3) 20)
	(= (fly-cost deposito refugio4) 13)
	(= (fly-cost deposito refugio5) 10)
	(= (fly-cost deposito refugio6) 3)
	(= (fly-cost deposito refugio7) 4)
	(= (fly-cost refugio1 deposito) 6)
	(= (fly-cost refugio1 refugio2) 12)
	(= (fly-cost refugio1 refugio3) 8)
	(= (fly-cost refugio1 refugio4) 8)
	(= (fly-cost refugio1 refugio5) 9)
	(= (fly-cost refugio1 refugio6) 7)
	(= (fly-cost refugio1 refugio7) 7)
	(= (fly-cost refugio2 deposito) 15)
	(= (fly-cost refugio2 refugio1) 11)
	(= (fly-cost refugio2 refugio3) 7)
	(= (fly-cost refugio2 refugio4) 9)
	(= (fly-cost refugio2 refugio5) 13)
	(= (fly-cost refugio2 refugio6) 17)
	(= (fly-cost refugio2 refugio7) 3)
	(= (fly-cost refugio3 deposito) 14)
	(= (fly-cost refugio3 refugio1) 20)
	(= (fly-cost refugio3 refugio2) 10)
	(= (fly-cost refugio3 refugio4) 2)
	(= (fly-cost refugio3 refugio5) 6)
	(= (fly-cost refugio3 refugio6) 2)
	(= (fly-cost refugio3 refugio7) 4)
	(= (fly-cost refugio4 deposito) 4)
	(= (fly-cost refugio4 refugio1) 6)
	(= (fly-cost refugio4 refugio2) 17)
	(= (fly-cost refugio4 refugio3) 8)
	(= (fly-cost refugio4 refugio5) 5)
	(= (fly-cost refugio4 refugio6) 19)
	(= (fly-cost refugio4 refugio7) 15)
	(= (fly-cost refugio5 deposito) 9)
	(= (fly-cost refugio5 refugio1) 2)
	(= (fly-cost refugio5 refugio2) 10)
	(= (fly-cost refugio5 refugio3) 7)
	(= (fly-cost refugio5 refugio4) 12)
	(= (fly-cost refugio5 refugio6) 13)
	(= (fly-cost refugio5 refugio7) 2)
	(= (fly-cost refugio6 deposito) 12)
	(= (fly-cost refugio6 refugio1) 10)
	(= (fly-cost refugio6 refugio2) 1)
	(= (fly-cost refugio6 refugio3) 16)
	(= (fly-cost refugio6 refugio4) 9)
	(= (fly-cost refugio6 refugio5) 14)
	(= (fly-cost refugio6 refugio7) 20)
	(= (fly-cost refugio7 deposito) 1)
	(= (fly-cost refugio7 refugio1) 16)
	(= (fly-cost refugio7 refugio2) 1)
	(= (fly-cost refugio7 refugio3) 4)
	(= (fly-cost refugio7 refugio4) 20)
	(= (fly-cost refugio7 refugio5) 5)
	(= (fly-cost refugio7 refugio6) 11)
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)
	(at-dron dron1 deposito)
	(free dron1)
	(at-carrier carrier1 deposito)
	(boxes-in-carrier carrier1 n0)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 comida)
	(at-box box6 deposito)
	(box-has box6 comida)
	(at-box box7 deposito)
	(box-has box7 medicina)
	(at-person person1 refugio1)
	(at-person person2 refugio4)
	(at-person person3 refugio4)
	(at-person person4 refugio4)
	(at-person person5 refugio6)
	(at-person person6 refugio5)
	(at-person person7 refugio2)
)

(:goal (and
	(person-has person1 comida)
	(person-has person3 comida)
	(person-has person3 medicina)
	(person-has person4 comida)
	(person-has person5 comida)
	(person-has person6 comida)
	(person-has person7 comida)
))
(:metric minimize (total-cost))
)