(define (problem problem_size8)
(:domain emergencias-costs)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 refugio8 - location
	box1 box2 box3 box4 box5 box6 box7 box8 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 person6 person7 person8 - person
	carrier1 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(= (total-cost) 0)
	(= (fly-cost deposito refugio1) 10)
	(= (fly-cost deposito refugio2) 8)
	(= (fly-cost deposito refugio3) 15)
	(= (fly-cost deposito refugio4) 14)
	(= (fly-cost deposito refugio5) 14)
	(= (fly-cost deposito refugio6) 10)
	(= (fly-cost deposito refugio7) 15)
	(= (fly-cost deposito refugio8) 18)
	(= (fly-cost refugio1 deposito) 1)
	(= (fly-cost refugio1 refugio2) 13)
	(= (fly-cost refugio1 refugio3) 19)
	(= (fly-cost refugio1 refugio4) 16)
	(= (fly-cost refugio1 refugio5) 1)
	(= (fly-cost refugio1 refugio6) 8)
	(= (fly-cost refugio1 refugio7) 18)
	(= (fly-cost refugio1 refugio8) 8)
	(= (fly-cost refugio2 deposito) 17)
	(= (fly-cost refugio2 refugio1) 1)
	(= (fly-cost refugio2 refugio3) 2)
	(= (fly-cost refugio2 refugio4) 4)
	(= (fly-cost refugio2 refugio5) 1)
	(= (fly-cost refugio2 refugio6) 6)
	(= (fly-cost refugio2 refugio7) 20)
	(= (fly-cost refugio2 refugio8) 17)
	(= (fly-cost refugio3 deposito) 19)
	(= (fly-cost refugio3 refugio1) 17)
	(= (fly-cost refugio3 refugio2) 9)
	(= (fly-cost refugio3 refugio4) 18)
	(= (fly-cost refugio3 refugio5) 17)
	(= (fly-cost refugio3 refugio6) 5)
	(= (fly-cost refugio3 refugio7) 15)
	(= (fly-cost refugio3 refugio8) 19)
	(= (fly-cost refugio4 deposito) 2)
	(= (fly-cost refugio4 refugio1) 1)
	(= (fly-cost refugio4 refugio2) 15)
	(= (fly-cost refugio4 refugio3) 8)
	(= (fly-cost refugio4 refugio5) 14)
	(= (fly-cost refugio4 refugio6) 13)
	(= (fly-cost refugio4 refugio7) 20)
	(= (fly-cost refugio4 refugio8) 16)
	(= (fly-cost refugio5 deposito) 15)
	(= (fly-cost refugio5 refugio1) 4)
	(= (fly-cost refugio5 refugio2) 19)
	(= (fly-cost refugio5 refugio3) 14)
	(= (fly-cost refugio5 refugio4) 2)
	(= (fly-cost refugio5 refugio6) 11)
	(= (fly-cost refugio5 refugio7) 19)
	(= (fly-cost refugio5 refugio8) 8)
	(= (fly-cost refugio6 deposito) 9)
	(= (fly-cost refugio6 refugio1) 16)
	(= (fly-cost refugio6 refugio2) 20)
	(= (fly-cost refugio6 refugio3) 20)
	(= (fly-cost refugio6 refugio4) 9)
	(= (fly-cost refugio6 refugio5) 1)
	(= (fly-cost refugio6 refugio7) 10)
	(= (fly-cost refugio6 refugio8) 15)
	(= (fly-cost refugio7 deposito) 8)
	(= (fly-cost refugio7 refugio1) 1)
	(= (fly-cost refugio7 refugio2) 19)
	(= (fly-cost refugio7 refugio3) 4)
	(= (fly-cost refugio7 refugio4) 11)
	(= (fly-cost refugio7 refugio5) 13)
	(= (fly-cost refugio7 refugio6) 14)
	(= (fly-cost refugio7 refugio8) 19)
	(= (fly-cost refugio8 deposito) 15)
	(= (fly-cost refugio8 refugio1) 8)
	(= (fly-cost refugio8 refugio2) 8)
	(= (fly-cost refugio8 refugio3) 17)
	(= (fly-cost refugio8 refugio4) 13)
	(= (fly-cost refugio8 refugio5) 12)
	(= (fly-cost refugio8 refugio6) 1)
	(= (fly-cost refugio8 refugio7) 1)
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)
	(at-dron dron1 deposito)
	(free dron1)
	(at-carrier carrier1 deposito)
	(boxes-in-carrier carrier1 n0)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 comida)
	(at-box box6 deposito)
	(box-has box6 comida)
	(at-box box7 deposito)
	(box-has box7 comida)
	(at-box box8 deposito)
	(box-has box8 medicina)
	(at-person person1 refugio6)
	(at-person person2 refugio4)
	(at-person person3 refugio3)
	(at-person person4 refugio3)
	(at-person person5 refugio8)
	(at-person person6 refugio1)
	(at-person person7 refugio8)
	(at-person person8 refugio1)
)

(:goal (and
	(person-has person1 comida)
	(person-has person2 comida)
	(person-has person3 medicina)
	(person-has person4 comida)
	(person-has person5 comida)
	(person-has person6 comida)
	(person-has person7 comida)
	(person-has person8 comida)
))
(:metric minimize (total-cost))
)