(define (problem problem_size9)
(:domain emergencias-costs)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 refugio8 refugio9 - location
	box1 box2 box3 box4 box5 box6 box7 box8 box9 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 person6 person7 person8 person9 - person
	carrier1 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(= (total-cost) 0)
	(= (fly-cost deposito refugio1) 1)
	(= (fly-cost deposito refugio2) 9)
	(= (fly-cost deposito refugio3) 7)
	(= (fly-cost deposito refugio4) 16)
	(= (fly-cost deposito refugio5) 6)
	(= (fly-cost deposito refugio6) 9)
	(= (fly-cost deposito refugio7) 5)
	(= (fly-cost deposito refugio8) 8)
	(= (fly-cost deposito refugio9) 14)
	(= (fly-cost refugio1 deposito) 7)
	(= (fly-cost refugio1 refugio2) 4)
	(= (fly-cost refugio1 refugio3) 9)
	(= (fly-cost refugio1 refugio4) 13)
	(= (fly-cost refugio1 refugio5) 18)
	(= (fly-cost refugio1 refugio6) 8)
	(= (fly-cost refugio1 refugio7) 3)
	(= (fly-cost refugio1 refugio8) 8)
	(= (fly-cost refugio1 refugio9) 15)
	(= (fly-cost refugio2 deposito) 16)
	(= (fly-cost refugio2 refugio1) 18)
	(= (fly-cost refugio2 refugio3) 13)
	(= (fly-cost refugio2 refugio4) 16)
	(= (fly-cost refugio2 refugio5) 13)
	(= (fly-cost refugio2 refugio6) 16)
	(= (fly-cost refugio2 refugio7) 12)
	(= (fly-cost refugio2 refugio8) 7)
	(= (fly-cost refugio2 refugio9) 6)
	(= (fly-cost refugio3 deposito) 19)
	(= (fly-cost refugio3 refugio1) 16)
	(= (fly-cost refugio3 refugio2) 6)
	(= (fly-cost refugio3 refugio4) 15)
	(= (fly-cost refugio3 refugio5) 7)
	(= (fly-cost refugio3 refugio6) 6)
	(= (fly-cost refugio3 refugio7) 7)
	(= (fly-cost refugio3 refugio8) 16)
	(= (fly-cost refugio3 refugio9) 7)
	(= (fly-cost refugio4 deposito) 16)
	(= (fly-cost refugio4 refugio1) 14)
	(= (fly-cost refugio4 refugio2) 8)
	(= (fly-cost refugio4 refugio3) 19)
	(= (fly-cost refugio4 refugio5) 12)
	(= (fly-cost refugio4 refugio6) 19)
	(= (fly-cost refugio4 refugio7) 14)
	(= (fly-cost refugio4 refugio8) 19)
	(= (fly-cost refugio4 refugio9) 1)
	(= (fly-cost refugio5 deposito) 16)
	(= (fly-cost refugio5 refugio1) 13)
	(= (fly-cost refugio5 refugio2) 4)
	(= (fly-cost refugio5 refugio3) 20)
	(= (fly-cost refugio5 refugio4) 17)
	(= (fly-cost refugio5 refugio6) 2)
	(= (fly-cost refugio5 refugio7) 5)
	(= (fly-cost refugio5 refugio8) 3)
	(= (fly-cost refugio5 refugio9) 10)
	(= (fly-cost refugio6 deposito) 5)
	(= (fly-cost refugio6 refugio1) 18)
	(= (fly-cost refugio6 refugio2) 4)
	(= (fly-cost refugio6 refugio3) 14)
	(= (fly-cost refugio6 refugio4) 6)
	(= (fly-cost refugio6 refugio5) 13)
	(= (fly-cost refugio6 refugio7) 12)
	(= (fly-cost refugio6 refugio8) 1)
	(= (fly-cost refugio6 refugio9) 10)
	(= (fly-cost refugio7 deposito) 7)
	(= (fly-cost refugio7 refugio1) 2)
	(= (fly-cost refugio7 refugio2) 16)
	(= (fly-cost refugio7 refugio3) 16)
	(= (fly-cost refugio7 refugio4) 18)
	(= (fly-cost refugio7 refugio5) 4)
	(= (fly-cost refugio7 refugio6) 16)
	(= (fly-cost refugio7 refugio8) 7)
	(= (fly-cost refugio7 refugio9) 12)
	(= (fly-cost refugio8 deposito) 6)
	(= (fly-cost refugio8 refugio1) 9)
	(= (fly-cost refugio8 refugio2) 8)
	(= (fly-cost refugio8 refugio3) 1)
	(= (fly-cost refugio8 refugio4) 7)
	(= (fly-cost refugio8 refugio5) 3)
	(= (fly-cost refugio8 refugio6) 18)
	(= (fly-cost refugio8 refugio7) 18)
	(= (fly-cost refugio8 refugio9) 10)
	(= (fly-cost refugio9 deposito) 5)
	(= (fly-cost refugio9 refugio1) 6)
	(= (fly-cost refugio9 refugio2) 15)
	(= (fly-cost refugio9 refugio3) 12)
	(= (fly-cost refugio9 refugio4) 18)
	(= (fly-cost refugio9 refugio5) 14)
	(= (fly-cost refugio9 refugio6) 8)
	(= (fly-cost refugio9 refugio7) 11)
	(= (fly-cost refugio9 refugio8) 20)
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)
	(at-dron dron1 deposito)
	(free dron1)
	(at-carrier carrier1 deposito)
	(boxes-in-carrier carrier1 n0)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 comida)
	(at-box box6 deposito)
	(box-has box6 comida)
	(at-box box7 deposito)
	(box-has box7 medicina)
	(at-box box8 deposito)
	(box-has box8 medicina)
	(at-box box9 deposito)
	(box-has box9 medicina)
	(at-person person1 refugio9)
	(at-person person2 refugio2)
	(at-person person3 refugio9)
	(at-person person4 refugio2)
	(at-person person5 refugio5)
	(at-person person6 refugio4)
	(at-person person7 refugio2)
	(at-person person8 refugio9)
	(at-person person9 refugio9)
)

(:goal (and
	(person-has person1 comida)
	(person-has person2 comida)
	(person-has person3 comida)
	(person-has person3 medicina)
	(person-has person4 comida)
	(person-has person5 comida)
	(person-has person5 medicina)
	(person-has person6 comida)
	(person-has person9 medicina)
))
(:metric minimize (total-cost))
)