(define (problem emergencias-size24)
    (:domain emergencias)

    (:objects
        dron1 - dron
        person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 person14 person15 person16 person17 person18 person19 person20 person21 person22 person23 person24 - person
        box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 box11 box12 box13 box14 box15 box16 box17 box18 box19 box20 box21 box22 box23 box24 - box
        comida medicina - bcontent
        deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 refugio8 refugio9 refugio10 refugio11 refugio12 refugio13 refugio14 refugio15 refugio16 refugio17 refugio18 refugio19 refugio20 refugio21 refugio22 refugio23 refugio24 - location
        izquierda derecha - grip
    )

    (:init
        (at-dron dron1 deposito)
        (at-box box1 deposito)
        (at-box box2 deposito)
        (at-box box3 deposito)
        (at-box box4 deposito)
        (at-box box5 deposito)
        (at-box box6 deposito)
        (at-box box7 deposito)
        (at-box box8 deposito)
        (at-box box9 deposito)
        (at-box box10 deposito)
        (at-box box11 deposito)
        (at-box box12 deposito)
        (at-box box13 deposito)
        (at-box box14 deposito)
        (at-box box15 deposito)
        (at-box box16 deposito)
        (at-box box17 deposito)
        (at-box box18 deposito)
        (at-box box19 deposito)
        (at-box box20 deposito)
        (at-box box21 deposito)
        (at-box box22 deposito)
        (at-box box23 deposito)
        (at-box box24 deposito)
        (at-person person1 refugio1)
        (at-person person2 refugio2)
        (at-person person3 refugio3)
        (at-person person4 refugio4)
        (at-person person5 refugio5)
        (at-person person6 refugio6)
        (at-person person7 refugio7)
        (at-person person8 refugio8)
        (at-person person9 refugio9)
        (at-person person10 refugio10)
        (at-person person11 refugio11)
        (at-person person12 refugio12)
        (at-person person13 refugio13)
        (at-person person14 refugio14)
        (at-person person15 refugio15)
        (at-person person16 refugio16)
        (at-person person17 refugio17)
        (at-person person18 refugio18)
        (at-person person19 refugio19)
        (at-person person20 refugio20)
        (at-person person21 refugio21)
        (at-person person22 refugio22)
        (at-person person23 refugio23)
        (at-person person24 refugio24)
        (box-has box1 comida)
        (box-has box2 medicina)
        (box-has box3 comida)
        (box-has box4 medicina)
        (box-has box5 comida)
        (box-has box6 medicina)
        (box-has box7 comida)
        (box-has box8 medicina)
        (box-has box9 comida)
        (box-has box10 medicina)
        (box-has box11 comida)
        (box-has box12 medicina)
        (box-has box13 comida)
        (box-has box14 medicina)
        (box-has box15 comida)
        (box-has box16 medicina)
        (box-has box17 comida)
        (box-has box18 medicina)
        (box-has box19 comida)
        (box-has box20 medicina)
        (box-has box21 comida)
        (box-has box22 medicina)
        (box-has box23 comida)
        (box-has box24 medicina)
        (need person1 comida)
        (need person2 medicina)
        (need person3 comida)
        (need person4 medicina)
        (need person5 comida)
        (need person6 medicina)
        (need person7 comida)
        (need person8 medicina)
        (need person9 comida)
        (need person10 medicina)
        (need person11 comida)
        (need person12 medicina)
        (need person13 comida)
        (need person14 medicina)
        (need person15 comida)
        (need person16 medicina)
        (need person17 comida)
        (need person18 medicina)
        (need person19 comida)
        (need person20 medicina)
        (need person21 comida)
        (need person22 medicina)
        (need person23 comida)
        (need person24 medicina)
        (free izquierda)
        (free derecha)
    )

    (:goal (and
        (person-has person1 comida)
        (person-has person2 medicina)
        (person-has person3 comida)
        (person-has person4 medicina)
        (person-has person5 comida)
        (person-has person6 medicina)
        (person-has person7 comida)
        (person-has person8 medicina)
        (person-has person9 comida)
        (person-has person10 medicina)
        (person-has person11 comida)
        (person-has person12 medicina)
        (person-has person13 comida)
        (person-has person14 medicina)
        (person-has person15 comida)
        (person-has person16 medicina)
        (person-has person17 comida)
        (person-has person18 medicina)
        (person-has person19 comida)
        (person-has person20 medicina)
        (person-has person21 comida)
        (person-has person22 medicina)
        (person-has person23 comida)
        (person-has person24 medicina)
    ))
)
