(define (problem problem_size13)
(:domain emergencias)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 refugio8 refugio9 refugio10 refugio11 refugio12 refugio13 - location
	box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 box11 box12 box13 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 - person
	dron1-izq dron1-der - grip
)

(:init
	(at-dron dron1 deposito)
	(free dron1-izq)
	(free dron1-der)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 comida)
	(at-box box6 deposito)
	(box-has box6 medicina)
	(at-box box7 deposito)
	(box-has box7 medicina)
	(at-box box8 deposito)
	(box-has box8 medicina)
	(at-box box9 deposito)
	(box-has box9 medicina)
	(at-box box10 deposito)
	(box-has box10 medicina)
	(at-box box11 deposito)
	(box-has box11 medicina)
	(at-box box12 deposito)
	(box-has box12 medicina)
	(at-box box13 deposito)
	(box-has box13 medicina)
	(at-person person1 refugio6)
	(at-person person2 refugio3)
	(at-person person3 refugio6)
	(at-person person4 refugio12)
	(at-person person5 refugio3)
	(at-person person6 refugio6)
	(at-person person7 refugio6)
	(at-person person8 refugio5)
	(at-person person9 refugio5)
	(at-person person10 refugio1)
	(at-person person11 refugio13)
	(at-person person12 refugio12)
	(at-person person13 refugio12)
)

(:goal (and
	(person-has person1 medicina)
	(person-has person2 comida)
	(person-has person2 medicina)
	(person-has person5 comida)
	(person-has person6 comida)
	(person-has person7 medicina)
	(person-has person8 comida)
	(person-has person8 medicina)
	(person-has person10 medicina)
	(person-has person11 medicina)
	(person-has person12 medicina)
	(person-has person13 comida)
	(person-has person13 medicina)
))
)
