(define (problem problem_size22)
(:domain emergencias)
(:objects
	dron1 - dron
	deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 refugio8 refugio9 refugio10 refugio11 refugio12 refugio13 refugio14 refugio15 refugio16 refugio17 refugio18 refugio19 refugio20 refugio21 refugio22 - location
	box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 box11 box12 box13 box14 box15 box16 box17 box18 box19 box20 box21 box22 - box
	comida medicina - bcontent
	person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 person14 person15 person16 person17 person18 person19 person20 person21 person22 - person
	dron1-izq dron1-der - grip
)

(:init
	(at-dron dron1 deposito)
	(free dron1-izq)
	(free dron1-der)
	(at-box box1 deposito)
	(box-has box1 comida)
	(at-box box2 deposito)
	(box-has box2 comida)
	(at-box box3 deposito)
	(box-has box3 comida)
	(at-box box4 deposito)
	(box-has box4 comida)
	(at-box box5 deposito)
	(box-has box5 comida)
	(at-box box6 deposito)
	(box-has box6 medicina)
	(at-box box7 deposito)
	(box-has box7 medicina)
	(at-box box8 deposito)
	(box-has box8 medicina)
	(at-box box9 deposito)
	(box-has box9 medicina)
	(at-box box10 deposito)
	(box-has box10 medicina)
	(at-box box11 deposito)
	(box-has box11 medicina)
	(at-box box12 deposito)
	(box-has box12 medicina)
	(at-box box13 deposito)
	(box-has box13 medicina)
	(at-box box14 deposito)
	(box-has box14 medicina)
	(at-box box15 deposito)
	(box-has box15 medicina)
	(at-box box16 deposito)
	(box-has box16 medicina)
	(at-box box17 deposito)
	(box-has box17 medicina)
	(at-box box18 deposito)
	(box-has box18 medicina)
	(at-box box19 deposito)
	(box-has box19 medicina)
	(at-box box20 deposito)
	(box-has box20 medicina)
	(at-box box21 deposito)
	(box-has box21 medicina)
	(at-box box22 deposito)
	(box-has box22 medicina)
	(at-person person1 refugio19)
	(at-person person2 refugio9)
	(at-person person3 refugio6)
	(at-person person4 refugio10)
	(at-person person5 refugio22)
	(at-person person6 refugio19)
	(at-person person7 refugio6)
	(at-person person8 refugio21)
	(at-person person9 refugio17)
	(at-person person10 refugio4)
	(at-person person11 refugio5)
	(at-person person12 refugio2)
	(at-person person13 refugio19)
	(at-person person14 refugio20)
	(at-person person15 refugio1)
	(at-person person16 refugio18)
	(at-person person17 refugio16)
	(at-person person18 refugio6)
	(at-person person19 refugio20)
	(at-person person20 refugio21)
	(at-person person21 refugio4)
	(at-person person22 refugio17)
)

(:goal (and
	(person-has person1 medicina)
	(person-has person2 medicina)
	(person-has person4 medicina)
	(person-has person6 medicina)
	(person-has person7 comida)
	(person-has person7 medicina)
	(person-has person8 medicina)
	(person-has person9 medicina)
	(person-has person10 comida)
	(person-has person10 medicina)
	(person-has person11 medicina)
	(person-has person12 medicina)
	(person-has person14 medicina)
	(person-has person15 comida)
	(person-has person15 medicina)
	(person-has person16 medicina)
	(person-has person17 medicina)
	(person-has person18 comida)
	(person-has person19 medicina)
	(person-has person20 medicina)
	(person-has person21 comida)
	(person-has person21 medicina)
))
)
