(define (problem emergencias-size12)
    (:domain emergencias)

    (:objects
        dron1 - dron
        person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 - person
        box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 box11 box12 - box
        comida medicina - bcontent
        deposito refugio1 refugio2 refugio3 refugio4 refugio5 refugio6 refugio7 refugio8 refugio9 refugio10 refugio11 refugio12 - location
        izquierda derecha - grip
    )

    (:init
        (at-dron dron1 deposito)
        (at-box box1 deposito)
        (at-box box2 deposito)
        (at-box box3 deposito)
        (at-box box4 deposito)
        (at-box box5 deposito)
        (at-box box6 deposito)
        (at-box box7 deposito)
        (at-box box8 deposito)
        (at-box box9 deposito)
        (at-box box10 deposito)
        (at-box box11 deposito)
        (at-box box12 deposito)
        (at-person person1 refugio1)
        (at-person person2 refugio2)
        (at-person person3 refugio3)
        (at-person person4 refugio4)
        (at-person person5 refugio5)
        (at-person person6 refugio6)
        (at-person person7 refugio7)
        (at-person person8 refugio8)
        (at-person person9 refugio9)
        (at-person person10 refugio10)
        (at-person person11 refugio11)
        (at-person person12 refugio12)
        (box-has box1 comida)
        (box-has box2 medicina)
        (box-has box3 comida)
        (box-has box4 medicina)
        (box-has box5 comida)
        (box-has box6 medicina)
        (box-has box7 comida)
        (box-has box8 medicina)
        (box-has box9 comida)
        (box-has box10 medicina)
        (box-has box11 comida)
        (box-has box12 medicina)
        (need person1 comida)
        (need person2 medicina)
        (need person3 comida)
        (need person4 medicina)
        (need person5 comida)
        (need person6 medicina)
        (need person7 comida)
        (need person8 medicina)
        (need person9 comida)
        (need person10 medicina)
        (need person11 comida)
        (need person12 medicina)
        (free izquierda)
        (free derecha)
    )

    (:goal (and
        (person-has person1 comida)
        (person-has person2 medicina)
        (person-has person3 comida)
        (person-has person4 medicina)
        (person-has person5 comida)
        (person-has person6 medicina)
        (person-has person7 comida)
        (person-has person8 medicina)
        (person-has person9 comida)
        (person-has person10 medicina)
        (person-has person11 comida)
        (person-has person12 medicina)
    ))
)
